In [1]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect
import pandas as pd
import numpy as np
import json

In [2]:
!ls

app.py
data_engineering.ipynb
data_engineering_updated.ipynb
flask_queries.ipynb
info_data
raw_data
README.md
refugees_and_conflict.sqlite
static
templates

In [3]:
engine = create_engine('sqlite:///refugees_and_conflict.sqlite')

In [4]:
Base = automap_base()

In [5]:
Base.prepare(engine, reflect = True)

In [6]:
Base.classes.keys()

['asylum', 'battle_deaths', 'info_table', 'origin']

In [7]:
session = Session(engine)

In [8]:
Asylum = Base.classes.asylum
BattleDeaths = Base.classes.battle_deaths
Origin = Base.classes.origin
InfoTable = Base.classes.info_table

In [27]:
samples_df = pd.read_sql_table('asylum', engine)
samples_df.head()

,id,country_name,country_lat,country_lon,country_code,y1990,y1991,y1992,y1993,y1994,...,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016,y2017
0,1,Albania,41.0000,20.0,ALB,0,0,3000,3000,3000,...,65,70,76,82,86,93,104,104,111,0
1,2,Algeria,28.0000,3.0,DZA,169110,169124,219314,219067,219073,...,94093,94137,94144,94148,94133,94150,94128,94182,94220,0
2,3,American Samoa,-14.3333,-170.0,ASM,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Andorra,42.5000,1.6,AND,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Angola,-12.5000,18.5,AGO,11557,11022,11002,10878,10686,...,12710,14734,15155,16223,23413,23783,15474,15555,15537,0

In [28]:
asylum_table = session.query(Asylum.country_name, Asylum.y1990, Asylum.y1991, 
                           Asylum.y1992, Asylum.y1993, Asylum.y1994, Asylum.y1995, Asylum.y1996,
                            Asylum.y1997, Asylum.y1998, Asylum.y1999, Asylum.y2000, Asylum.y2001,
                            Asylum.y2002, Asylum.y2003, Asylum.y2004, Asylum.y2005, Asylum.y2006, 
                            Asylum.y2007, Asylum.y2008, Asylum.y2009, Asylum.y2010, Asylum.y2011, 
                            Asylum.y2012, Asylum.y2013, Asylum.y2014, Asylum.y2015, Asylum.y2016).all()

In [29]:
asylum_table = pd.DataFrame(asylum_table)
asylum_table.head()

,country_name,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,...,y2007,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,Albania,0,0,3000,3000,3000,4720,4925,30,22332,...,77,65,70,76,82,86,93,104,104,111
1,Algeria,169110,169124,219314,219067,219073,192489,190267,170746,165226,...,94137,94093,94137,94144,94148,94133,94150,94128,94182,94220
2,American Samoa,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Andorra,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Angola,11557,11022,11002,10878,10686,10884,9381,9364,10605,...,12069,12710,14734,15155,16223,23413,23783,15474,15555,15537

In [30]:
asylum_table = asylum_table.set_index('country_name').to_dict('index')

In [35]:
asylum_table

{'Afghanistan': {'y1990': 50,
  'y1991': 38,
  'y1992': 60025,
  'y1993': 32132,
  'y1994': 19131,
  'y1995': 19605,
  'y1996': 18775,
  'y1997': 5,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 6,
  'y2002': 3,
  'y2003': 22,
  'y2004': 30,
  'y2005': 32,
  'y2006': 35,
  'y2007': 42,
  'y2008': 37,
  'y2009': 37,
  'y2010': 6434,
  'y2011': 3009,
  'y2012': 16187,
  'y2013': 16863,
  'y2014': 300423,
  'y2015': 257554,
  'y2016': 59770},
 'Albania': {'y1990': 0,
  'y1991': 0,
  'y1992': 3000,
  'y1993': 3000,
  'y1994': 3000,
  'y1995': 4720,
  'y1996': 4925,
  'y1997': 30,
  'y1998': 22332,
  'y1999': 3930,
  'y2000': 523,
  'y2001': 292,
  'y2002': 17,
  'y2003': 26,
  'y2004': 51,
  'y2005': 56,
  'y2006': 56,
  'y2007': 77,
  'y2008': 65,
  'y2009': 70,
  'y2010': 76,
  'y2011': 82,
  'y2012': 86,
  'y2013': 93,
  'y2014': 104,
  'y2015': 104,
  'y2016': 111},
 'Algeria': {'y1990': 169110,
  'y1991': 169124,
  'y1992': 219314,
  'y1993': 219067,
  'y1994': 219073,
  'y1995': 192489,
  'y1996': 190267,
  'y1997': 170746,
  'y1998': 165226,
  'y1999': 165249,
  'y2000': 169656,
  'y2001': 169422,
  'y2002': 169233,
  'y2003': 169033,
  'y2004': 169048,
  'y2005': 94101,
  'y2006': 94180,
  'y2007': 94137,
  'y2008': 94093,
  'y2009': 94137,
  'y2010': 94144,
  'y2011': 94148,
  'y2012': 94133,
  'y2013': 94150,
  'y2014': 94128,
  'y2015': 94182,
  'y2016': 94220},
 'American Samoa': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 0,
  'y2016': 0},
 'Andorra': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 0,
  'y2016': 0},
 'Angola': {'y1990': 11557,
  'y1991': 11022,
  'y1992': 11002,
  'y1993': 10878,
  'y1994': 10686,
  'y1995': 10884,
  'y1996': 9381,
  'y1997': 9364,
  'y1998': 10605,
  'y1999': 13071,
  'y2000': 12086,
  'y2001': 12250,
  'y2002': 12250,
  'y2003': 13382,
  'y2004': 13970,
  'y2005': 13984,
  'y2006': 13090,
  'y2007': 12069,
  'y2008': 12710,
  'y2009': 14734,
  'y2010': 15155,
  'y2011': 16223,
  'y2012': 23413,
  'y2013': 23783,
  'y2014': 15474,
  'y2015': 15555,
  'y2016': 15537},
 'Antigua and Barbuda': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 15,
  'y2016': 0},
 'Argentina': {'y1990': 11735,
  'y1991': 11529,
  'y1992': 11515,
  'y1993': 11636,
  'y1994': 11901,
  'y1995': 10314,
  'y1996': 10430,
  'y1997': 10522,
  'y1998': 2270,
  'y1999': 2345,
  'y2000': 2396,
  'y2001': 2396,
  'y2002': 2439,
  'y2003': 2642,
  'y2004': 2916,
  'y2005': 3074,
  'y2006': 3158,
  'y2007': 3263,
  'y2008': 2845,
  'y2009': 3230,
  'y2010': 3276,
  'y2011': 3361,
  'y2012': 3488,
  'y2013': 3362,
  'y2014': 3498,
  'y2015': 3207,
  'y2016': 3222},
 'Armenia': {'y1990': 0,
  'y1991': 0,
  'y1992': 300000,
  'y1993': 334000,
  'y1994': 304039,
  'y1995': 218950,
  'y1996': 218950,
  'y1997': 219000,
  'y1998': 310012,
  'y1999': 296216,
  'y2000': 280591,
  'y2001': 264337,
  'y2002': 247550,
  'y2003': 239289,
  'y2004': 235235,
  'y2005': 219550,
  'y2006': 113714,
  'y2007': 4566,
  'y2008': 3953,
  'y2009': 3607,
  'y2010': 3296,
  'y2011': 2918,
  'y2012': 2854,
  'y2013': 13732,
  'y2014': 17640,
  'y2015': 19319,
  'y2016': 17873},
 'Aruba': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 1,
  'y2014': 0,
  'y2015': 2,
  'y2016': 0},
 'Australia': {'y1990': 97915,
  'y1991': 53117,
  'y1992': 52604,
  'y1993': 53505,
  'y1994': 57575,
  'y1995': 62145,
  'y1996': 67313,
  'y1997': 66074,
  'y1998': 69745,
  'y1999': 64918,
  'y2000': 60246,
  'y2001': 57895,
  'y2002': 59436,
  'y2003': 56258,
  'y2004': 63476,
  'y2005': 64964,
  'y2006': 68948,
  'y2007': 22164,
  'y2008': 20919,
  'y2009': 22548,
  'y2010': 21805,
  'y2011': 23434,
  'y2012': 30083,
  'y2013': 34503,
  'y2014': 35582,
  'y2015': 36917,
  'y2016': 42107},
 'Austria': {'y1990': 34938,
  'y1991': 34508,
  'y1992': 62355,
  'y1993': 57687,
  'y1994': 40703,
  'y1995': 34385,
  'y1996': 89116,
  'y1997': 84394,
  'y1998': 80300,
  'y1999': 82081,
  'y2000': 15492,
  'y2001': 14390,
  'y2002': 14130,
  'y2003': 16109,
  'y2004': 17795,
  'y2005': 21230,
  'y2006': 25486,
  'y2007': 30773,
  'y2008': 37557,
  'y2009': 38906,
  'y2010': 42630,
  'y2011': 47073,
  'y2012': 51730,
  'y2013': 55598,
  'y2014': 60747,
  'y2015': 72216,
  'y2016': 93182},
 'Azerbaijan': {'y1990': 0,
  'y1991': 0,
  'y1992': 246000,
  'y1993': 228840,
  'y1994': 231635,
  'y1995': 233682,
  'y1996': 233692,
  'y1997': 233715,
  'y1998': 221635,
  'y1999': 221643,
  'y2000': 287,
  'y2001': 367,
  'y2002': 458,
  'y2003': 326,
  'y2004': 8606,
  'y2005': 3004,
  'y2006': 2618,
  'y2007': 2352,
  'y2008': 2061,
  'y2009': 1642,
  'y2010': 1891,
  'y2011': 1730,
  'y2012': 1468,
  'y2013': 1380,
  'y2014': 1299,
  'y2015': 1278,
  'y2016': 1183},
 'Bahrain': {'y1990': 1780,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 1,
  'y2000': 1,
  'y2001': 1,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 1,
  'y2007': 0,
  'y2008': 48,
  'y2009': 139,
  'y2010': 165,
  'y2011': 199,
  'y2012': 289,
  'y2013': 294,
  'y2014': 311,
  'y2015': 247,
  'y2016': 270},
 'Bangladesh': {'y1990': 145,
  'y1991': 40260,
  'y1992': 245154,
  'y1993': 198954,
  'y1994': 116228,
  'y1995': 51118,
  'y1996': 30692,
  'y1997': 21603,
  'y1998': 22277,
  'y1999': 22210,
  'y2000': 21627,
  'y2001': 22173,
  'y2002': 22025,
  'y2003': 19792,
  'y2004': 20449,
  'y2005': 21098,
  'y2006': 26311,
  'y2007': 27573,
  'y2008': 28389,
  'y2009': 228586,
  'y2010': 229253,
  'y2011': 229669,
  'y2012': 230697,
  'y2013': 231145,
  'y2014': 232472,
  'y2015': 231958,
  'y2016': 276198},
 'Barbados': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 1,
  'y2014': 1,
  'y2015': 0,
  'y2016': 0},
 'Belarus': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 1822,
  'y1995': 28988,
  'y1996': 30525,
  'y1997': 50,
  'y1998': 75,
  'y1999': 260,
  'y2000': 458,
  'y2001': 584,
  'y2002': 618,
  'y2003': 638,
  'y2004': 725,
  'y2005': 725,
  'y2006': 690,
  'y2007': 649,
  'y2008': 609,
  'y2009': 580,
  'y2010': 589,
  'y2011': 595,
  'y2012': 576,
  'y2013': 604,
  'y2014': 925,
  'y2015': 1809,
  'y2016': 1632},
 'Belgium': {'y1990': 25911,
  'y1991': 24071,
  'y1992': 24292,
  'y1993': 24908,
  'y1994': 19497,
  'y1995': 31691,
  'y1996': 36060,
  'y1997': 36060,
  'y1998': 15509,
  'y1999': 16760,
  'y2000': 18832,
  'y2001': 12265,
  'y2002': 12578,
  'y2003': 12595,
  'y2004': 13529,
  'y2005': 15282,
  'y2006': 16820,
  'y2007': 17575,
  'y2008': 17026,
  'y2009': 15545,
  'y2010': 17892,
  'y2011': 22402,
  'y2012': 22024,
  'y2013': 25629,
  'y2014': 29179,
  'y2015': 35314,
  'y2016': 42128},
 'Belize': {'y1990': 30657,
  'y1991': 29969,
  'y1992': 20351,
  'y1993': 8912,
  'y1994': 8857,
  'y1995': 8750,
  'y1996': 8534,
  'y1997': 8387,
  'y1998': 3483,
  'y1999': 2891,
  'y2000': 1250,
  'y2001': 1129,
  'y2002': 1049,
  'y2003': 861,
  'y2004': 732,
  'y2005': 624,
  'y2006': 488,
  'y2007': 358,
  'y2008': 277,
  'y2009': 230,
  'y2010': 134,
  'y2011': 78,
  'y2012': 28,
  'y2013': 21,
  'y2014': 10,
  'y2015': 35,
  'y2016': 0},
 'Benin': {'y1990': 456,
  'y1991': 456,
  'y1992': 293,
  'y1993': 156241,
  'y1994': 70406,
  'y1995': 23843,
  'y1996': 5960,
  'y1997': 2918,
  'y1998': 2903,
  'y1999': 3657,
  'y2000': 4296,
  'y2001': 4799,
  'y2002': 5021,
  'y2003': 5034,
  'y2004': 4802,
  'y2005': 30294,
  'y2006': 10797,
  'y2007': 7621,
  'y2008': 6933,
  'y2009': 7205,
  'y2010': 7139,
  'y2011': 7217,
  'y2012': 4966,
  'y2013': 194,
  'y2014': 415,
  'y2015': 530,
  'y2016': 799},
 'Bermuda': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 0,
  'y2016': 0},
 'Bhutan': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 0,
  'y2016': 0},
 'Bosnia and Herzegovina': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 40000,
  'y1998': 40000,
  'y1999': 65645,
  'y2000': 38152,
  'y2001': 32745,
  'y2002': 28022,
  'y2003': 22517,
  'y2004': 22215,
  'y2005': 10568,
  'y2006': 10318,
  'y2007': 7367,
  'y2008': 7257,
  'y2009': 7132,
  'y2010': 7016,
  'y2011': 6933,
  'y2012': 6903,
  'y2013': 6926,
  'y2014': 6890,
  'y2015': 6798,
  'y2016': 5256},
 'Botswana': {'y1990': 1179,
  'y1991': 1054,
  'y1992': 497,
  'y1993': 514,
  'y1994': 503,
  'y1995': 266,
  'y1996': 214,
  'y1997': 281,
  'y1998': 2137,
  'y1999': 1296,
  'y2000': 3551,
  'y2001': 3581,
  'y2002': 2805,
  'y2003': 2838,
  'y2004': 2839,
  'y2005': 3109,
  'y2006': 3160,
  'y2007': 2465,
  'y2008': 3019,
  'y2009': 3022,
  'y2010': 2986,
  'y2011': 3312,
  'y2012': 2785,
  'y2013': 2773,
  'y2014': 2645,
  'y2015': 2130,
  'y2016': 2080},
 'Brazil': {'y1990': 5335,
  'y1991': 5389,
  'y1992': 5439,
  'y1993': 6198,
  'y1994': 2223,
  'y1995': 2050,
  'y1996': 2212,
  'y1997': 2260,
  'y1998': 2347,
  'y1999': 2378,
  'y2000': 2722,
  'y2001': 2884,
  'y2002': 3182,
  'y2003': 3193,
  'y2004': 3345,
  'y2005': 3458,
  'y2006': 3492,
  'y2007': 20783,
  'y2008': 3852,
  'y2009': 4232,
  'y2010': 4357,
  'y2011': 4477,
  'y2012': 4689,
  'y2013': 5196,
  'y2014': 7490,
  'y2015': 8707,
  'y2016': 9634},
 'Brunei Darussalam': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 0,
  'y2016': 0},
 'Bulgaria': {'y1990': 0,
  'y1991': 0,
  'y1992': 218,
  'y1993': 450,
  'y1994': 1060,
  'y1995': 1320,
  'y1996': 1430,
  'y1997': 390,
  'y1998': 240,
  'y1999': 547,
  'y2000': 1474,
  'y2001': 3004,
  'y2002': 3658,
  'y2003': 4068,
  'y2004': 4684,
  'y2005': 4413,
  'y2006': 4504,
  'y2007': 4836,
  'y2008': 5129,
  'y2009': 5393,
  'y2010': 5530,
  'y2011': 5688,
  'y2012': 2288,
  'y2013': 4320,
  'y2014': 11046,
  'y2015': 16557,
  'y2016': 17774},
 'Burkina Faso': {'y1990': 350,
  'y1991': 320,
  'y1992': 5670,
  'y1993': 6604,
  'y1994': 49990,
  'y1995': 29777,
  'y1996': 28381,
  'y1997': 1801,
  'y1998': 564,
  'y1999': 675,
  'y2000': 696,
  'y2001': 457,
  'y2002': 457,
  'y2003': 466,
  'y2004': 492,
  'y2005': 511,
  'y2006': 511,
  'y2007': 535,
  'y2008': 557,
  'y2009': 543,
  'y2010': 531,
  'y2011': 546,
  'y2012': 39306,
  'y2013': 29234,
  'y2014': 31894,
  'y2015': 34017,
  'y2016': 32546},
 'Burundi': {'y1990': 268403,
  'y1991': 270136,
  'y1992': 271745,
  'y1993': 271883,
  'y1994': 300302,
  'y1995': 173017,
  'y1996': 20733,
  'y1997': 22028,
  'y1998': 25093,
  'y1999': 22109,
  'y2000': 27136,
  'y2001': 27896,
  'y2002': 40533,
  'y2003': 40971,
  'y2004': 48808,
  'y2005': 20681,
  'y2006': 13176,
  'y2007': 24483,
  'y2008': 21093,
  'y2009': 24967,
  'y2010': 29365,
  'y2011': 35659,
  'y2012': 41813,
  'y2013': 45490,
  'y2014': 52936,
  'y2015': 53363,
  'y2016': 57462},
 'Cambodia': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 5,
  'y1994': 10,
  'y1995': 15,
  'y1996': 16,
  'y1997': 14,
  'y1998': 21,
  'y1999': 21,
  'y2000': 34,
  'y2001': 50,
  'y2002': 200,
  'y2003': 76,
  'y2004': 382,
  'y2005': 127,
  'y2006': 99,
  'y2007': 179,
  'y2008': 164,
  'y2009': 135,
  'y2010': 129,
  'y2011': 64,
  'y2012': 77,
  'y2013': 68,
  'y2014': 63,
  'y2015': 76,
  'y2016': 61},
 'Cameroon': {'y1990': 49876,
  'y1991': 45237,
  'y1992': 42233,
  'y1993': 44013,
  'y1994': 44036,
  'y1995': 45781,
  'y1996': 46407,
  'y1997': 47057,
  'y1998': 47826,
  'y1999': 49227,
  'y2000': 43680,
  'y2001': 41186,
  'y2002': 58288,
  'y2003': 58583,
  'y2004': 58861,
  'y2005': 52042,
  'y2006': 35083,
  'y2007': 60137,
  'y2008': 81037,
  'y2009': 99957,
  'y2010': 104275,
  'y2011': 100373,
  'y2012': 98969,
  'y2013': 114753,
  'y2014': 264126,
  'y2015': 342973,
  'y2016': 375393},
 'Canada': {'y1990': 154761,
  'y1991': 170916,
  'y1992': 183723,
  'y1993': 183241,
  'y1994': 186563,
  'y1995': 152125,
  'y1996': 138435,
  'y1997': 125184,
  'y1998': 119371,
  'y1999': 123316,
  'y2000': 126991,
  'y2001': 129224,
  'y2002': 129950,
  'y2003': 133094,
  'y2004': 141398,
  'y2005': 147171,
  'y2006': 151827,
  'y2007': 175741,
  'y2008': 173651,
  'y2009': 169434,
  'y2010': 165549,
  'y2011': 164883,
  'y2012': 163756,
  'y2013': 160349,
  'y2014': 149163,
  'y2015': 135888,
  'y2016': 97311},
 'Cayman Islands': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 0,
  'y2000': 0,
  'y2001': 0,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 0,
  'y2006': 0,
  'y2007': 0,
  'y2008': 0,
  'y2009': 1,
  'y2010': 1,
  'y2011': 3,
  'y2012': 3,
  'y2013': 6,
  'y2014': 6,
  'y2015': 12,
  'y2016': 13},
 'Central African Republic': {'y1990': 4284,
  'y1991': 12223,
  'y1992': 19040,
  'y1993': 44129,
  'y1994': 47791,
  'y1995': 33856,
  'y1996': 36564,
  'y1997': 38499,
  'y1998': 43013,
  'y1999': 49314,
  'y2000': 55661,
  'y2001': 49239,
  'y2002': 50725,
  'y2003': 44753,
  'y2004': 25020,
  'y2005': 24569,
  'y2006': 12357,
  'y2007': 7535,
  'y2008': 7429,
  'y2009': 27047,
  'y2010': 21574,
  'y2011': 16730,
  'y2012': 14014,
  'y2013': 14322,
  'y2014': 7694,
  'y2015': 7330,
  'y2016': 12107},
 'Chad': {'y1990': 0,
  'y1991': 0,
  'y1992': 70,
  'y1993': 70,
  'y1994': 109,
  'y1995': 100,
  'y1996': 100,
  'y1997': 302,
  'y1998': 8810,
  'y1999': 23478,
  'y2000': 17692,
  'y2001': 12950,
  'y2002': 33455,
  'y2003': 146400,
  'y2004': 259880,
  'y2005': 275412,
  'y2006': 286743,
  'y2007': 294017,
  'y2008': 330510,
  'y2009': 338495,
  'y2010': 347939,
  'y2011': 366494,
  'y2012': 373695,
  'y2013': 434479,
  'y2014': 452897,
  'y2015': 369540,
  'y2016': 391235},
 'Chile': {'y1990': 58,
  'y1991': 72,
  'y1992': 142,
  'y1993': 239,
  'y1994': 217,
  'y1995': 283,
  'y1996': 313,
  'y1997': 276,
  'y1998': 305,
  'y1999': 323,
  'y2000': 364,
  'y2001': 389,
  'y2002': 413,
  'y2003': 466,
  'y2004': 569,
  'y2005': 806,
  'y2006': 1134,
  'y2007': 1376,
  'y2008': 1613,
  'y2009': 1539,
  'y2010': 1621,
  'y2011': 1674,
  'y2012': 1695,
  'y2013': 1743,
  'y2014': 1773,
  'y2015': 1849,
  'y2016': 1716},
 'China': {'y1990': 287276,
  'y1991': 289061,
  'y1992': 288123,
  'y1993': 287423,
  'y1994': 287066,
  'y1995': 288309,
  'y1996': 290100,
  'y1997': 291507,
  'y1998': 292345,
  'y1999': 293299,
  'y2000': 294110,
  'y2001': 295325,
  'y2002': 297277,
  'y2003': 299354,
  'y2004': 299375,
  'y2005': 301041,
  'y2006': 301027,
  'y2007': 301078,
  'y2008': 300967,
  'y2009': 300989,
  'y2010': 300986,
  'y2011': 301018,
  'y2012': 301037,
  'y2013': 301047,
  'y2014': 301052,
  'y2015': 301052,
  'y2016': 317239},
 'Colombia': {'y1990': 460,
  'y1991': 450,
  'y1992': 478,
  'y1993': 298,
  'y1994': 316,
  'y1995': 218,
  'y1996': 220,
  'y1997': 223,
  'y1998': 226,
  'y1999': 230,
  'y2000': 239,
  'y2001': 210,
  'y2002': 205,
  'y2003': 186,
  'y2004': 141,
  'y2005': 155,
  'y2006': 143,
  'y2007': 168,
  'y2008': 170,
  'y2009': 196,
  'y2010': 212,
  'y2011': 219,
  'y2012': 219,
  'y2013': 224,
  'y2014': 213,
  'y2015': 226,
  'y2016': 221},
 'Comoros': {'y1990': 0,
  'y1991': 0,
  'y1992': 0,
  'y1993': 0,
  'y1994': 0,
  'y1995': 0,
  'y1996': 0,
  'y1997': 0,
  'y1998': 0,
  'y1999': 9,
  'y2000': 11,
  'y2001': 13,
  'y2002': 0,
  'y2003': 0,
  'y2004': 0,
  'y2005': 1,
  'y2006': 1,
  'y2007': 0,
  'y2008': 0,
  'y2009': 0,
  'y2010': 0,
  'y2011': 0,
  'y2012': 0,
  'y2013': 0,
  'y2014': 0,
  'y2015': 0,
  'y2016': 0},
 'Costa Rica': {'y1990': 276210,
  'y1991': 117492,
  'y1992': 114392,
  'y1993': 24834,
  'y1994': 24630,
  'y1995': 24226,
  'y1996': 23176,
  'y1997': 23114,
  'y1998': 22986,
  'y1999': 22903,
  'y2000': 5519,
  'y2001': 8104,
  'y2002': 12433,
  'y2003': 13508,
  'y2004': 10413,
  'y2005': 11253,
  'y2006': 11515,
  'y2007': 17190,
  'y2008': 18136,
  'y2009': 19116,
  'y2010': 19505,
  'y2011': 20057,
  'y2012': 20449,
  'y2013': 20569,
  'y2014': 20744,
  'y2015': 3616,
  'y2016': 4152},
 'Croatia': {'y1990': 0,
  'y1991': 0,
  'y1992': 403000,
  'y1993': 287000,
  'y1994': 183600,
  'y1995': 198647,
  'y1996': 165395,
  'y1997': 68863,
  'y1998': 29027,
  'y1999': 28374,
  'y2000': 22437,
  'y2001': 21875,
  'y2002': 8392,
  'y2003': 4387,
  'y2004': 3663,
  'y2005': 2927,
  'y2006': 2443,
  'y2007': 1642,
  'y2008': 1597,
  'y2009': 1238,
  'y2010': 936,
  'y2011': 824,
  'y2012': 724,
  'y2013': 684,
  'y2014': 726,
  'y2015': 522,
  'y2016': 255},
 'Cuba': {'y1990': 3988,
  'y1991': 0,
  'y1992': 5092,
  'y1993': 3606,
  'y1994': 2002,
  'y1995': 1829,
  'y1996': 1694,
  'y1997': 1280,
  'y1998': 1067,
  'y1999': 967,
  'y2000': 954,
  'y2001': 1036,
  'y2002': 1005,
  'y2003': 836,
  'y2004': 795,
  'y2005': 706,
  'y2006': 667,
  'y2007': 615,
  'y2008': 525,
  'y2009': 454,
  'y2010': 411,
  'y2011': 384,
  'y2012': 371,
  'y2013': 384,
  'y2014': 280,
  'y2015': 303,
  'y2016': 312},
 'Cyprus': {'y1990': 33,
  'y1991': 60,
  'y1992': 80,
  'y1993': 82,
  'y1994': 66,
  'y1995': 55,
  'y1996': 49,
  'y1997': 43,
  'y1998': 84,
  'y1999': 117,
  'y2000': 76,
  'y2001': 83,
  'y2002': 173,
  'y2003': 349,
  'y2004': 531,
  'y2005': 701,
  'y2006': 924,
  'y2007': 1194,
  'y2008': 1465,
  'y2009': 2888,
  'y2010': 3394,
  'y2011': 3503,
  'y2012': 3631,
  'y2013': 3883,
  'y2014': 5126,
  'y2015': 7067,
  'y2016': 8433},
 'Czech Republic': {'y1990': 0,
  'y1991': 691,
  'y1992': 9399,
  'y1993': 188,
  'y1994': 1186,
  'y1995': 2655,
  'y1996': 2266,
  'y1997': 1731,
  'y1998': 1805,
  'y1999': 1232,
  'y2000': 1186,
  'y2001': 1216,
  'y2002': 1297,
  'y2003': 1516,
  'y2004': 1144,
  'y2005': 1802,
  'y2006': 1887,
  'y2007': 2037,
  'y2008': 2110,
  'y2009': 2323,

In [38]:
for key, value in asylum_table.items():
    print("Key:")
    print(key)
    print(value)

Key:
Albania
{'y1990': 0, 'y1991': 0, 'y1992': 3000, 'y1993': 3000, 'y1994': 3000, 'y1995': 4720, 'y1996': 4925, 'y1997': 30, 'y1998': 22332, 'y1999': 3930, 'y2000': 523, 'y2001': 292, 'y2002': 17, 'y2003': 26, 'y2004': 51, 'y2005': 56, 'y2006': 56, 'y2007': 77, 'y2008': 65, 'y2009': 70, 'y2010': 76, 'y2011': 82, 'y2012': 86, 'y2013': 93, 'y2014': 104, 'y2015': 104, 'y2016': 111}
Key:
Algeria
{'y1990': 169110, 'y1991': 169124, 'y1992': 219314, 'y1993': 219067, 'y1994': 219073, 'y1995': 192489, 'y1996': 190267, 'y1997': 170746, 'y1998': 165226, 'y1999': 165249, 'y2000': 169656, 'y2001': 169422, 'y2002': 169233, 'y2003': 169033, 'y2004': 169048, 'y2005': 94101, 'y2006': 94180, 'y2007': 94137, 'y2008': 94093, 'y2009': 94137, 'y2010': 94144, 'y2011': 94148, 'y2012': 94133, 'y2013': 94150, 'y2014': 94128, 'y2015': 94182, 'y2016': 94220}
Key:
American Samoa
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Andorra
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Angola
{'y1990': 11557, 'y1991': 11022, 'y1992': 11002, 'y1993': 10878, 'y1994': 10686, 'y1995': 10884, 'y1996': 9381, 'y1997': 9364, 'y1998': 10605, 'y1999': 13071, 'y2000': 12086, 'y2001': 12250, 'y2002': 12250, 'y2003': 13382, 'y2004': 13970, 'y2005': 13984, 'y2006': 13090, 'y2007': 12069, 'y2008': 12710, 'y2009': 14734, 'y2010': 15155, 'y2011': 16223, 'y2012': 23413, 'y2013': 23783, 'y2014': 15474, 'y2015': 15555, 'y2016': 15537}
Key:
Antigua and Barbuda
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 15, 'y2016': 0}
Key:
Argentina
{'y1990': 11735, 'y1991': 11529, 'y1992': 11515, 'y1993': 11636, 'y1994': 11901, 'y1995': 10314, 'y1996': 10430, 'y1997': 10522, 'y1998': 2270, 'y1999': 2345, 'y2000': 2396, 'y2001': 2396, 'y2002': 2439, 'y2003': 2642, 'y2004': 2916, 'y2005': 3074, 'y2006': 3158, 'y2007': 3263, 'y2008': 2845, 'y2009': 3230, 'y2010': 3276, 'y2011': 3361, 'y2012': 3488, 'y2013': 3362, 'y2014': 3498, 'y2015': 3207, 'y2016': 3222}
Key:
Armenia
{'y1990': 0, 'y1991': 0, 'y1992': 300000, 'y1993': 334000, 'y1994': 304039, 'y1995': 218950, 'y1996': 218950, 'y1997': 219000, 'y1998': 310012, 'y1999': 296216, 'y2000': 280591, 'y2001': 264337, 'y2002': 247550, 'y2003': 239289, 'y2004': 235235, 'y2005': 219550, 'y2006': 113714, 'y2007': 4566, 'y2008': 3953, 'y2009': 3607, 'y2010': 3296, 'y2011': 2918, 'y2012': 2854, 'y2013': 13732, 'y2014': 17640, 'y2015': 19319, 'y2016': 17873}
Key:
Aruba
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 1, 'y2014': 0, 'y2015': 2, 'y2016': 0}
Key:
Australia
{'y1990': 97915, 'y1991': 53117, 'y1992': 52604, 'y1993': 53505, 'y1994': 57575, 'y1995': 62145, 'y1996': 67313, 'y1997': 66074, 'y1998': 69745, 'y1999': 64918, 'y2000': 60246, 'y2001': 57895, 'y2002': 59436, 'y2003': 56258, 'y2004': 63476, 'y2005': 64964, 'y2006': 68948, 'y2007': 22164, 'y2008': 20919, 'y2009': 22548, 'y2010': 21805, 'y2011': 23434, 'y2012': 30083, 'y2013': 34503, 'y2014': 35582, 'y2015': 36917, 'y2016': 42107}
Key:
Austria
{'y1990': 34938, 'y1991': 34508, 'y1992': 62355, 'y1993': 57687, 'y1994': 40703, 'y1995': 34385, 'y1996': 89116, 'y1997': 84394, 'y1998': 80300, 'y1999': 82081, 'y2000': 15492, 'y2001': 14390, 'y2002': 14130, 'y2003': 16109, 'y2004': 17795, 'y2005': 21230, 'y2006': 25486, 'y2007': 30773, 'y2008': 37557, 'y2009': 38906, 'y2010': 42630, 'y2011': 47073, 'y2012': 51730, 'y2013': 55598, 'y2014': 60747, 'y2015': 72216, 'y2016': 93182}
Key:
Azerbaijan
{'y1990': 0, 'y1991': 0, 'y1992': 246000, 'y1993': 228840, 'y1994': 231635, 'y1995': 233682, 'y1996': 233692, 'y1997': 233715, 'y1998': 221635, 'y1999': 221643, 'y2000': 287, 'y2001': 367, 'y2002': 458, 'y2003': 326, 'y2004': 8606, 'y2005': 3004, 'y2006': 2618, 'y2007': 2352, 'y2008': 2061, 'y2009': 1642, 'y2010': 1891, 'y2011': 1730, 'y2012': 1468, 'y2013': 1380, 'y2014': 1299, 'y2015': 1278, 'y2016': 1183}
Key:
Bahrain
{'y1990': 1780, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 1, 'y2000': 1, 'y2001': 1, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 1, 'y2007': 0, 'y2008': 48, 'y2009': 139, 'y2010': 165, 'y2011': 199, 'y2012': 289, 'y2013': 294, 'y2014': 311, 'y2015': 247, 'y2016': 270}
Key:
Bangladesh
{'y1990': 145, 'y1991': 40260, 'y1992': 245154, 'y1993': 198954, 'y1994': 116228, 'y1995': 51118, 'y1996': 30692, 'y1997': 21603, 'y1998': 22277, 'y1999': 22210, 'y2000': 21627, 'y2001': 22173, 'y2002': 22025, 'y2003': 19792, 'y2004': 20449, 'y2005': 21098, 'y2006': 26311, 'y2007': 27573, 'y2008': 28389, 'y2009': 228586, 'y2010': 229253, 'y2011': 229669, 'y2012': 230697, 'y2013': 231145, 'y2014': 232472, 'y2015': 231958, 'y2016': 276198}
Key:
Barbados
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 1, 'y2014': 1, 'y2015': 0, 'y2016': 0}
Key:
Belarus
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 1822, 'y1995': 28988, 'y1996': 30525, 'y1997': 50, 'y1998': 75, 'y1999': 260, 'y2000': 458, 'y2001': 584, 'y2002': 618, 'y2003': 638, 'y2004': 725, 'y2005': 725, 'y2006': 690, 'y2007': 649, 'y2008': 609, 'y2009': 580, 'y2010': 589, 'y2011': 595, 'y2012': 576, 'y2013': 604, 'y2014': 925, 'y2015': 1809, 'y2016': 1632}
Key:
Belgium
{'y1990': 25911, 'y1991': 24071, 'y1992': 24292, 'y1993': 24908, 'y1994': 19497, 'y1995': 31691, 'y1996': 36060, 'y1997': 36060, 'y1998': 15509, 'y1999': 16760, 'y2000': 18832, 'y2001': 12265, 'y2002': 12578, 'y2003': 12595, 'y2004': 13529, 'y2005': 15282, 'y2006': 16820, 'y2007': 17575, 'y2008': 17026, 'y2009': 15545, 'y2010': 17892, 'y2011': 22402, 'y2012': 22024, 'y2013': 25629, 'y2014': 29179, 'y2015': 35314, 'y2016': 42128}
Key:
Belize
{'y1990': 30657, 'y1991': 29969, 'y1992': 20351, 'y1993': 8912, 'y1994': 8857, 'y1995': 8750, 'y1996': 8534, 'y1997': 8387, 'y1998': 3483, 'y1999': 2891, 'y2000': 1250, 'y2001': 1129, 'y2002': 1049, 'y2003': 861, 'y2004': 732, 'y2005': 624, 'y2006': 488, 'y2007': 358, 'y2008': 277, 'y2009': 230, 'y2010': 134, 'y2011': 78, 'y2012': 28, 'y2013': 21, 'y2014': 10, 'y2015': 35, 'y2016': 0}
Key:
Benin
{'y1990': 456, 'y1991': 456, 'y1992': 293, 'y1993': 156241, 'y1994': 70406, 'y1995': 23843, 'y1996': 5960, 'y1997': 2918, 'y1998': 2903, 'y1999': 3657, 'y2000': 4296, 'y2001': 4799, 'y2002': 5021, 'y2003': 5034, 'y2004': 4802, 'y2005': 30294, 'y2006': 10797, 'y2007': 7621, 'y2008': 6933, 'y2009': 7205, 'y2010': 7139, 'y2011': 7217, 'y2012': 4966, 'y2013': 194, 'y2014': 415, 'y2015': 530, 'y2016': 799}
Key:
Bermuda
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Bhutan
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Bosnia and Herzegovina
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 40000, 'y1998': 40000, 'y1999': 65645, 'y2000': 38152, 'y2001': 32745, 'y2002': 28022, 'y2003': 22517, 'y2004': 22215, 'y2005': 10568, 'y2006': 10318, 'y2007': 7367, 'y2008': 7257, 'y2009': 7132, 'y2010': 7016, 'y2011': 6933, 'y2012': 6903, 'y2013': 6926, 'y2014': 6890, 'y2015': 6798, 'y2016': 5256}
Key:
Botswana
{'y1990': 1179, 'y1991': 1054, 'y1992': 497, 'y1993': 514, 'y1994': 503, 'y1995': 266, 'y1996': 214, 'y1997': 281, 'y1998': 2137, 'y1999': 1296, 'y2000': 3551, 'y2001': 3581, 'y2002': 2805, 'y2003': 2838, 'y2004': 2839, 'y2005': 3109, 'y2006': 3160, 'y2007': 2465, 'y2008': 3019, 'y2009': 3022, 'y2010': 2986, 'y2011': 3312, 'y2012': 2785, 'y2013': 2773, 'y2014': 2645, 'y2015': 2130, 'y2016': 2080}
Key:
Brazil
{'y1990': 5335, 'y1991': 5389, 'y1992': 5439, 'y1993': 6198, 'y1994': 2223, 'y1995': 2050, 'y1996': 2212, 'y1997': 2260, 'y1998': 2347, 'y1999': 2378, 'y2000': 2722, 'y2001': 2884, 'y2002': 3182, 'y2003': 3193, 'y2004': 3345, 'y2005': 3458, 'y2006': 3492, 'y2007': 20783, 'y2008': 3852, 'y2009': 4232, 'y2010': 4357, 'y2011': 4477, 'y2012': 4689, 'y2013': 5196, 'y2014': 7490, 'y2015': 8707, 'y2016': 9634}
Key:
Brunei Darussalam
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Bulgaria
{'y1990': 0, 'y1991': 0, 'y1992': 218, 'y1993': 450, 'y1994': 1060, 'y1995': 1320, 'y1996': 1430, 'y1997': 390, 'y1998': 240, 'y1999': 547, 'y2000': 1474, 'y2001': 3004, 'y2002': 3658, 'y2003': 4068, 'y2004': 4684, 'y2005': 4413, 'y2006': 4504, 'y2007': 4836, 'y2008': 5129, 'y2009': 5393, 'y2010': 5530, 'y2011': 5688, 'y2012': 2288, 'y2013': 4320, 'y2014': 11046, 'y2015': 16557, 'y2016': 17774}
Key:
Burkina Faso
{'y1990': 350, 'y1991': 320, 'y1992': 5670, 'y1993': 6604, 'y1994': 49990, 'y1995': 29777, 'y1996': 28381, 'y1997': 1801, 'y1998': 564, 'y1999': 675, 'y2000': 696, 'y2001': 457, 'y2002': 457, 'y2003': 466, 'y2004': 492, 'y2005': 511, 'y2006': 511, 'y2007': 535, 'y2008': 557, 'y2009': 543, 'y2010': 531, 'y2011': 546, 'y2012': 39306, 'y2013': 29234, 'y2014': 31894, 'y2015': 34017, 'y2016': 32546}
Key:
Burundi
{'y1990': 268403, 'y1991': 270136, 'y1992': 271745, 'y1993': 271883, 'y1994': 300302, 'y1995': 173017, 'y1996': 20733, 'y1997': 22028, 'y1998': 25093, 'y1999': 22109, 'y2000': 27136, 'y2001': 27896, 'y2002': 40533, 'y2003': 40971, 'y2004': 48808, 'y2005': 20681, 'y2006': 13176, 'y2007': 24483, 'y2008': 21093, 'y2009': 24967, 'y2010': 29365, 'y2011': 35659, 'y2012': 41813, 'y2013': 45490, 'y2014': 52936, 'y2015': 53363, 'y2016': 57462}
Key:
Cambodia
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 5, 'y1994': 10, 'y1995': 15, 'y1996': 16, 'y1997': 14, 'y1998': 21, 'y1999': 21, 'y2000': 34, 'y2001': 50, 'y2002': 200, 'y2003': 76, 'y2004': 382, 'y2005': 127, 'y2006': 99, 'y2007': 179, 'y2008': 164, 'y2009': 135, 'y2010': 129, 'y2011': 64, 'y2012': 77, 'y2013': 68, 'y2014': 63, 'y2015': 76, 'y2016': 61}
Key:
Cameroon
{'y1990': 49876, 'y1991': 45237, 'y1992': 42233, 'y1993': 44013, 'y1994': 44036, 'y1995': 45781, 'y1996': 46407, 'y1997': 47057, 'y1998': 47826, 'y1999': 49227, 'y2000': 43680, 'y2001': 41186, 'y2002': 58288, 'y2003': 58583, 'y2004': 58861, 'y2005': 52042, 'y2006': 35083, 'y2007': 60137, 'y2008': 81037, 'y2009': 99957, 'y2010': 104275, 'y2011': 100373, 'y2012': 98969, 'y2013': 114753, 'y2014': 264126, 'y2015': 342973, 'y2016': 375393}
Key:
Canada
{'y1990': 154761, 'y1991': 170916, 'y1992': 183723, 'y1993': 183241, 'y1994': 186563, 'y1995': 152125, 'y1996': 138435, 'y1997': 125184, 'y1998': 119371, 'y1999': 123316, 'y2000': 126991, 'y2001': 129224, 'y2002': 129950, 'y2003': 133094, 'y2004': 141398, 'y2005': 147171, 'y2006': 151827, 'y2007': 175741, 'y2008': 173651, 'y2009': 169434, 'y2010': 165549, 'y2011': 164883, 'y2012': 163756, 'y2013': 160349, 'y2014': 149163, 'y2015': 135888, 'y2016': 97311}
Key:
Cayman Islands
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 1, 'y2010': 1, 'y2011': 3, 'y2012': 3, 'y2013': 6, 'y2014': 6, 'y2015': 12, 'y2016': 13}
Key:
Central African Republic
{'y1990': 4284, 'y1991': 12223, 'y1992': 19040, 'y1993': 44129, 'y1994': 47791, 'y1995': 33856, 'y1996': 36564, 'y1997': 38499, 'y1998': 43013, 'y1999': 49314, 'y2000': 55661, 'y2001': 49239, 'y2002': 50725, 'y2003': 44753, 'y2004': 25020, 'y2005': 24569, 'y2006': 12357, 'y2007': 7535, 'y2008': 7429, 'y2009': 27047, 'y2010': 21574, 'y2011': 16730, 'y2012': 14014, 'y2013': 14322, 'y2014': 7694, 'y2015': 7330, 'y2016': 12107}
Key:
Chad
{'y1990': 0, 'y1991': 0, 'y1992': 70, 'y1993': 70, 'y1994': 109, 'y1995': 100, 'y1996': 100, 'y1997': 302, 'y1998': 8810, 'y1999': 23478, 'y2000': 17692, 'y2001': 12950, 'y2002': 33455, 'y2003': 146400, 'y2004': 259880, 'y2005': 275412, 'y2006': 286743, 'y2007': 294017, 'y2008': 330510, 'y2009': 338495, 'y2010': 347939, 'y2011': 366494, 'y2012': 373695, 'y2013': 434479, 'y2014': 452897, 'y2015': 369540, 'y2016': 391235}
Key:
Chile
{'y1990': 58, 'y1991': 72, 'y1992': 142, 'y1993': 239, 'y1994': 217, 'y1995': 283, 'y1996': 313, 'y1997': 276, 'y1998': 305, 'y1999': 323, 'y2000': 364, 'y2001': 389, 'y2002': 413, 'y2003': 466, 'y2004': 569, 'y2005': 806, 'y2006': 1134, 'y2007': 1376, 'y2008': 1613, 'y2009': 1539, 'y2010': 1621, 'y2011': 1674, 'y2012': 1695, 'y2013': 1743, 'y2014': 1773, 'y2015': 1849, 'y2016': 1716}
Key:
China
{'y1990': 287276, 'y1991': 289061, 'y1992': 288123, 'y1993': 287423, 'y1994': 287066, 'y1995': 288309, 'y1996': 290100, 'y1997': 291507, 'y1998': 292345, 'y1999': 293299, 'y2000': 294110, 'y2001': 295325, 'y2002': 297277, 'y2003': 299354, 'y2004': 299375, 'y2005': 301041, 'y2006': 301027, 'y2007': 301078, 'y2008': 300967, 'y2009': 300989, 'y2010': 300986, 'y2011': 301018, 'y2012': 301037, 'y2013': 301047, 'y2014': 301052, 'y2015': 301052, 'y2016': 317239}
Key:
Colombia
{'y1990': 460, 'y1991': 450, 'y1992': 478, 'y1993': 298, 'y1994': 316, 'y1995': 218, 'y1996': 220, 'y1997': 223, 'y1998': 226, 'y1999': 230, 'y2000': 239, 'y2001': 210, 'y2002': 205, 'y2003': 186, 'y2004': 141, 'y2005': 155, 'y2006': 143, 'y2007': 168, 'y2008': 170, 'y2009': 196, 'y2010': 212, 'y2011': 219, 'y2012': 219, 'y2013': 224, 'y2014': 213, 'y2015': 226, 'y2016': 221}
Key:
Comoros
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 9, 'y2000': 11, 'y2001': 13, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 1, 'y2006': 1, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Costa Rica
{'y1990': 276210, 'y1991': 117492, 'y1992': 114392, 'y1993': 24834, 'y1994': 24630, 'y1995': 24226, 'y1996': 23176, 'y1997': 23114, 'y1998': 22986, 'y1999': 22903, 'y2000': 5519, 'y2001': 8104, 'y2002': 12433, 'y2003': 13508, 'y2004': 10413, 'y2005': 11253, 'y2006': 11515, 'y2007': 17190, 'y2008': 18136, 'y2009': 19116, 'y2010': 19505, 'y2011': 20057, 'y2012': 20449, 'y2013': 20569, 'y2014': 20744, 'y2015': 3616, 'y2016': 4152}
Key:
Croatia
{'y1990': 0, 'y1991': 0, 'y1992': 403000, 'y1993': 287000, 'y1994': 183600, 'y1995': 198647, 'y1996': 165395, 'y1997': 68863, 'y1998': 29027, 'y1999': 28374, 'y2000': 22437, 'y2001': 21875, 'y2002': 8392, 'y2003': 4387, 'y2004': 3663, 'y2005': 2927, 'y2006': 2443, 'y2007': 1642, 'y2008': 1597, 'y2009': 1238, 'y2010': 936, 'y2011': 824, 'y2012': 724, 'y2013': 684, 'y2014': 726, 'y2015': 522, 'y2016': 255}
Key:
Cuba
{'y1990': 3988, 'y1991': 0, 'y1992': 5092, 'y1993': 3606, 'y1994': 2002, 'y1995': 1829, 'y1996': 1694, 'y1997': 1280, 'y1998': 1067, 'y1999': 967, 'y2000': 954, 'y2001': 1036, 'y2002': 1005, 'y2003': 836, 'y2004': 795, 'y2005': 706, 'y2006': 667, 'y2007': 615, 'y2008': 525, 'y2009': 454, 'y2010': 411, 'y2011': 384, 'y2012': 371, 'y2013': 384, 'y2014': 280, 'y2015': 303, 'y2016': 312}
Key:
Cyprus
{'y1990': 33, 'y1991': 60, 'y1992': 80, 'y1993': 82, 'y1994': 66, 'y1995': 55, 'y1996': 49, 'y1997': 43, 'y1998': 84, 'y1999': 117, 'y2000': 76, 'y2001': 83, 'y2002': 173, 'y2003': 349, 'y2004': 531, 'y2005': 701, 'y2006': 924, 'y2007': 1194, 'y2008': 1465, 'y2009': 2888, 'y2010': 3394, 'y2011': 3503, 'y2012': 3631, 'y2013': 3883, 'y2014': 5126, 'y2015': 7067, 'y2016': 8433}
Key:
Czech Republic
{'y1990': 0, 'y1991': 691, 'y1992': 9399, 'y1993': 188, 'y1994': 1186, 'y1995': 2655, 'y1996': 2266, 'y1997': 1731, 'y1998': 1805, 'y1999': 1232, 'y2000': 1186, 'y2001': 1216, 'y2002': 1297, 'y2003': 1516, 'y2004': 1144, 'y2005': 1802, 'y2006': 1887, 'y2007': 2037, 'y2008': 2110, 'y2009': 2323, 'y2010': 2449, 'y2011': 2449, 'y2012': 2805, 'y2013': 2979, 'y2014': 3137, 'y2015': 3644, 'y2016': 3580}
Key:
Denmark
{'y1990': 32906, 'y1991': 36110, 'y1992': 39118, 'y1993': 44564, 'y1994': 49558, 'y1995': 64844, 'y1996': 66373, 'y1997': 68122, 'y1998': 69015, 'y1999': 69006, 'y2000': 71035, 'y2001': 73284, 'y2002': 73597, 'y2003': 69858, 'y2004': 65310, 'y2005': 44374, 'y2006': 36659, 'y2007': 26788, 'y2008': 23401, 'y2009': 20355, 'y2010': 17922, 'y2011': 13399, 'y2012': 11814, 'y2013': 13170, 'y2014': 17785, 'y2015': 27326, 'y2016': 33436}
Key:
Djibouti
{'y1990': 77606, 'y1991': 96144, 'y1992': 28000, 'y1993': 34065, 'y1994': 33406, 'y1995': 27310, 'y1996': 25076, 'y1997': 23590, 'y1998': 23582, 'y1999': 23271, 'y2000': 23243, 'y2001': 23176, 'y2002': 21702, 'y2003': 27034, 'y2004': 18035, 'y2005': 10456, 'y2006': 9259, 'y2007': 6651, 'y2008': 9228, 'y2009': 12111, 'y2010': 15104, 'y2011': 20340, 'y2012': 19139, 'y2013': 20015, 'y2014': 20530, 'y2015': 19365, 'y2016': 17678}
Key:
Dominica
{'y1990': 0, 'y1991': 0, 'y1992': 0, 'y1993': 0, 'y1994': 0, 'y1995': 0, 'y1996': 0, 'y1997': 0, 'y1998': 0, 'y1999': 0, 'y2000': 0, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 0, 'y2011': 0, 'y2012': 0, 'y2013': 0, 'y2014': 0, 'y2015': 0, 'y2016': 0}
Key:
Dominican Republic
{'y1990': 1966, 'y1991': 1571, 'y1992': 510, 'y1993': 1331, 'y1994': 1252, 'y1995': 985, 'y1996': 640, 'y1997': 638, 'y1998': 614, 'y1999': 625, 'y2000': 510, 'y2001': 0, 'y2002': 0, 'y2003': 0, 'y2004': 0, 'y2005': 0, 'y2006': 0, 'y2007': 0, 'y2008': 0, 'y2009': 0, 'y2010': 599, 'y2011': 595, 'y2012': 758, 'y2013': 721, 'y2014': 608, 'y2015': 615, 'y2016': 578}
Key:
Ecuador
{'y1990': 510, 'y1991': 280, 'y1992': 204, 'y1993': 238, 'y1994': 244, 'y1995': 202, 'y1996': 211, 'y1997': 227, 'y1998': 248, 'y1999': 314, 'y2000': 1602, 'y2001': 1715, 'y2002': 3240, 'y2003': 6381, 'y2004': 8450, 'y2005': 10063, 'y2006': 11789, 'y2007': 264907, 'y2008': 101398, 'y2009': 116557, 'y2010': 121249, 'y2011': 123436, 'y2012': 123824, 'y2013': 123209, 'y2014': 122161, 'y2015': 121535, 'y2016': 102848}
Key:
El Salvador
{'y1990': 20300, 'y1991': 20099, 'y1992': 19903, 'y1993': 163, 'y1994': 156, 'y1995': 154, 'y1996': 150, 'y1997': 109, 'y1998': 33, 'y1999': 24, 'y2000': 59, 'y2001': 69, 'y2002': 74, 'y2003': 246, 'y2004': 235, 'y2005': 49, 'y2006': 39, 'y2007': 39, 'y2008': 32, 'y2009': 30, 'y2010': 38, 'y2011': 38, 'y2012': 45, 'y2013': 44, 'y2014': 35, 'y2015': 48, 'y2016': 36}
Key:
Equatorial Guinea

## Query Country Names

In [10]:
country_names = session.query(Asylum.country_name).all()
country_names = [x[0] for x in country_names]
country_names

['Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Polynesia',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Zambia',
 'Zimbabwe',
 'Afghanistan']

## Query Info Table

In [11]:
samples_df = pd.read_sql_table('info_table', engine)
samples_df.head()

,id,country_name,gdp_YR2015,population_YR2016,asylum_YR2016,origin_YR2016
0,1,Afghanistan,19215562178.9798,34656,17980,2501410
1,2,Albania,11335264966.561,2876,0,11050
2,3,Algeria,165874330876.321,40606,86,3675
3,4,American Samoa,659000000,56,0,0
4,5,Andorra,2811489408.89431,77,0,0

In [12]:
first_row_samples = session.query(InfoTable).first()
first_row_samples.__dict__

{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x266bb03a128>,
 'asylum_YR2016': 17980,
 'country_name': 'Afghanistan',
 'gdp_YR2015': '19215562178.9798',
 'id': 1,
 'origin_YR2016': 2501410,
 'population_YR2016': '34656'}

In [13]:
info_table = session.query(InfoTable.country_name, InfoTable.gdp_YR2015, InfoTable.population_YR2016, 
                           InfoTable.asylum_YR2016, InfoTable.origin_YR2016).all()

In [14]:
info_table = pd.DataFrame(info_table)
info_table.head()

,country_name,gdp_YR2015,population_YR2016,asylum_YR2016,origin_YR2016
0,Afghanistan,19215562178.9798,34656,17980,2501410
1,Albania,11335264966.561,2876,0,11050
2,Algeria,165874330876.321,40606,86,3675
3,American Samoa,659000000,56,0,0
4,Andorra,2811489408.89431,77,0,0

In [15]:
info_table.columns = ['country_name', 'GDP YEAR 2015', 'POPULATION YEAR 2016', 'ASYLUM NUMBER YEAR 2016', 'REFUGEE ORIGIN YEAR 2016']

In [16]:
info_table = info_table.set_index('country_name').to_dict('index')

In [17]:
info_table

{'Afghanistan': {'ASYLUM NUMBER YEAR 2016': 17980,
  'GDP YEAR 2015': '19215562178.9798',
  'POPULATION YEAR 2016': '34656',
  'REFUGEE ORIGIN YEAR 2016': 2501410},
 'Albania': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '11335264966.561',
  'POPULATION YEAR 2016': '2876',
  'REFUGEE ORIGIN YEAR 2016': 11050},
 'Algeria': {'ASYLUM NUMBER YEAR 2016': 86,
  'GDP YEAR 2015': '165874330876.321',
  'POPULATION YEAR 2016': '40606',
  'REFUGEE ORIGIN YEAR 2016': 3675},
 'American Samoa': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '659000000',
  'POPULATION YEAR 2016': '56',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Andorra': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2811489408.89431',
  'POPULATION YEAR 2016': '77',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Angola': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '102962245246.708',
  'POPULATION YEAR 2016': '28813',
  'REFUGEE ORIGIN YEAR 2016': 8363},
 'Antigua and Barbuda': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1364863037.03704',
  'POPULATION YEAR 2016': '101',
  'REFUGEE ORIGIN YEAR 2016': 77},
 'Argentina': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '584711485367.267',
  'POPULATION YEAR 2016': '43847',
  'REFUGEE ORIGIN YEAR 2016': 115},
 'Armenia': {'ASYLUM NUMBER YEAR 2016': 4,
  'GDP YEAR 2015': '10553337672.9872',
  'POPULATION YEAR 2016': '2925',
  'REFUGEE ORIGIN YEAR 2016': 10687},
 'Aruba': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '105',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Australia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1345383143356.35',
  'POPULATION YEAR 2016': '24127',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Austria': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '382065930307.978',
  'POPULATION YEAR 2016': '8747',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Azerbaijan': {'ASYLUM NUMBER YEAR 2016': 137,
  'GDP YEAR 2015': '53074370486.0433',
  'POPULATION YEAR 2016': '9762',
  'REFUGEE ORIGIN YEAR 2016': 10087},
 'Bahamas, The': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '11240000000',
  'POPULATION YEAR 2016': '391',
  'REFUGEE ORIGIN YEAR 2016': 293},
 'Bahrain': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '31125851063.8298',
  'POPULATION YEAR 2016': '1425',
  'REFUGEE ORIGIN YEAR 2016': 446},
 'Bangladesh': {'ASYLUM NUMBER YEAR 2016': 39,
  'GDP YEAR 2015': '195078665827.565',
  'POPULATION YEAR 2016': '162952',
  'REFUGEE ORIGIN YEAR 2016': 13810},
 'Barbados': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '4584150000',
  'POPULATION YEAR 2016': '285',
  'REFUGEE ORIGIN YEAR 2016': 144},
 'Belarus': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '56454734396.5842',
  'POPULATION YEAR 2016': '9507',
  'REFUGEE ORIGIN YEAR 2016': 3824},
 'Belgium': {'ASYLUM NUMBER YEAR 2016': 2,
  'GDP YEAR 2015': '455200045095.643',
  'POPULATION YEAR 2016': '11348',
  'REFUGEE ORIGIN YEAR 2016': 44},
 'Belize': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1742545900',
  'POPULATION YEAR 2016': '367',
  'REFUGEE ORIGIN YEAR 2016': 53},
 'Benin': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '8290986804.45245',
  'POPULATION YEAR 2016': '10872',
  'REFUGEE ORIGIN YEAR 2016': 464},
 'Bermuda': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '65',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Bhutan': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2059258652.94668',
  'POPULATION YEAR 2016': '798',
  'REFUGEE ORIGIN YEAR 2016': 11732},
 'Bolivia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '33000198263.3864',
  'POPULATION YEAR 2016': '10888',
  'REFUGEE ORIGIN YEAR 2016': 515},
 'Bosnia and Herzegovina': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '16209702863.6235',
  'POPULATION YEAR 2016': '3517',
  'REFUGEE ORIGIN YEAR 2016': 18179},
 'Botswana': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '14430573505.3797',
  'POPULATION YEAR 2016': '2250',
  'REFUGEE ORIGIN YEAR 2016': 265},
 'Brazil': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1803652649613.75',
  'POPULATION YEAR 2016': '207653',
  'REFUGEE ORIGIN YEAR 2016': 793},
 'British Virgin Islands': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '31',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Brunei Darussalam': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '12930394937.8137',
  'POPULATION YEAR 2016': '423',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Bulgaria': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '50199117547.0415',
  'POPULATION YEAR 2016': '7128',
  'REFUGEE ORIGIN YEAR 2016': 794},
 'Burkina Faso': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '10419303761.3524',
  'POPULATION YEAR 2016': '18646',
  'REFUGEE ORIGIN YEAR 2016': 2327},
 'Burundi': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '3066681386.73841',
  'POPULATION YEAR 2016': '10524',
  'REFUGEE ORIGIN YEAR 2016': 408036},
 'Cabo Verde': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1574288667.69981',
  'POPULATION YEAR 2016': '540',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Cambodia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '18049954289.4229',
  'POPULATION YEAR 2016': '15762',
  'REFUGEE ORIGIN YEAR 2016': 12408},
 'Cameroon': {'ASYLUM NUMBER YEAR 2016': 181,
  'GDP YEAR 2015': '30916218544.4404',
  'POPULATION YEAR 2016': '23439',
  'REFUGEE ORIGIN YEAR 2016': 10328},
 'Canada': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1552807652015.37',
  'POPULATION YEAR 2016': '36286',
  'REFUGEE ORIGIN YEAR 2016': 76},
 'Cayman Islands': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '61',
  'REFUGEE ORIGIN YEAR 2016': 6},
 'Central African Republic': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1583776759.97697',
  'POPULATION YEAR 2016': '4595',
  'REFUGEE ORIGIN YEAR 2016': 490869},
 'Chad': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '10888798113.7866',
  'POPULATION YEAR 2016': '14453',
  'REFUGEE ORIGIN YEAR 2016': 14146},
 'Channel Islands': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '165',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Chile': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '242517905161.664',
  'POPULATION YEAR 2016': '17910',
  'REFUGEE ORIGIN YEAR 2016': 490},
 'China': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '11064666282625.5',
  'POPULATION YEAR 2016': '1378665',
  'REFUGEE ORIGIN YEAR 2016': 207733},
 'Colombia': {'ASYLUM NUMBER YEAR 2016': 30,
  'GDP YEAR 2015': '291519596338.693',
  'POPULATION YEAR 2016': '48653',
  'REFUGEE ORIGIN YEAR 2016': 311051},
 'Comoros': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '565689764.63263',
  'POPULATION YEAR 2016': '796',
  'REFUGEE ORIGIN YEAR 2016': 557},
 'Congo, Dem. Rep.': {'ASYLUM NUMBER YEAR 2016': 261,
  'GDP YEAR 2015': '36188521106.9294',
  'POPULATION YEAR 2016': '78736',
  'REFUGEE ORIGIN YEAR 2016': 537429},
 'Congo, Rep.': {'ASYLUM NUMBER YEAR 2016': 51,
  'GDP YEAR 2015': '8553154580.39951',
  'POPULATION YEAR 2016': '5126',
  'REFUGEE ORIGIN YEAR 2016': 13231},
 'Costa Rica': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '54840103850.265',
  'POPULATION YEAR 2016': '4857',
  'REFUGEE ORIGIN YEAR 2016': 197},
 'Croatia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '48921877447.764',
  'POPULATION YEAR 2016': '4171',
  'REFUGEE ORIGIN YEAR 2016': 26211},
 'Cuba': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '87132800000',
  'POPULATION YEAR 2016': '11476',
  'REFUGEE ORIGIN YEAR 2016': 5925},
 'Cyprus': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '19676167239.6584',
  'POPULATION YEAR 2016': '1170',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Czech Republic': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '186829940545.759',
  'POPULATION YEAR 2016': '10562',
  'REFUGEE ORIGIN YEAR 2016': 1266},
 'Denmark': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '301298464861.385',
  'POPULATION YEAR 2016': '5731',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Djibouti': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1727000000',
  'POPULATION YEAR 2016': '942',
  'REFUGEE ORIGIN YEAR 2016': 1417},
 'Dominica': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '535095846.296296',
  'POPULATION YEAR 2016': '74',
  'REFUGEE ORIGIN YEAR 2016': 20},
 'Dominican Republic': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '68102618092.1031',
  'POPULATION YEAR 2016': '10649',
  'REFUGEE ORIGIN YEAR 2016': 344},
 'Ecuador': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '99290381000',
  'POPULATION YEAR 2016': '16385',
  'REFUGEE ORIGIN YEAR 2016': 1021},
 'Egypt, Arab Rep.': {'ASYLUM NUMBER YEAR 2016': 268,
  'GDP YEAR 2015': '332698041030.807',
  'POPULATION YEAR 2016': '95689',
  'REFUGEE ORIGIN YEAR 2016': 19742},
 'El Salvador': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '26052340000',
  'POPULATION YEAR 2016': '6345',
  'REFUGEE ORIGIN YEAR 2016': 19595},
 'Equatorial Guinea': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '12597210657.5048',
  'POPULATION YEAR 2016': '1221',
  'REFUGEE ORIGIN YEAR 2016': 126},
 'Eritrea': {'ASYLUM NUMBER YEAR 2016': 25,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '4955',
  'REFUGEE ORIGIN YEAR 2016': 459390},
 'Estonia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '22566956982.229',
  'POPULATION YEAR 2016': '1316',
  'REFUGEE ORIGIN YEAR 2016': 298},
 'Ethiopia': {'ASYLUM NUMBER YEAR 2016': 50,
  'GDP YEAR 2015': '64464547915.2698',
  'POPULATION YEAR 2016': '102403',
  'REFUGEE ORIGIN YEAR 2016': 83894},
 'Faroe Islands': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2476746087.18917',
  'POPULATION YEAR 2016': '49',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Fiji': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '4391113415.33181',
  'POPULATION YEAR 2016': '899',
  'REFUGEE ORIGIN YEAR 2016': 791},
 'Finland': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '232439324529.645',
  'POPULATION YEAR 2016': '5495',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'France': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2433562015516.21',
  'POPULATION YEAR 2016': '66896',
  'REFUGEE ORIGIN YEAR 2016': 45},
 'French Polynesia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '280',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Gabon': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '14262032470.9041',
  'POPULATION YEAR 2016': '1980',
  'REFUGEE ORIGIN YEAR 2016': 152},
 'Gambia, The': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '907652509.516259',
  'POPULATION YEAR 2016': '2039',
  'REFUGEE ORIGIN YEAR 2016': 11569},
 'Georgia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '13993546732.4726',
  'POPULATION YEAR 2016': '3719',
  'REFUGEE ORIGIN YEAR 2016': 6365},
 'Germany': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '3375611100742.22',
  'POPULATION YEAR 2016': '82668',
  'REFUGEE ORIGIN YEAR 2016': 67},
 'Ghana': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '37543361203.5609',
  'POPULATION YEAR 2016': '28207',
  'REFUGEE ORIGIN YEAR 2016': 15507},
 'Gibraltar': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '34',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Greece': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '195541761243.144',
  'POPULATION YEAR 2016': '10747',
  'REFUGEE ORIGIN YEAR 2016': 101},
 'Greenland': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2220380802.33059',
  'POPULATION YEAR 2016': '56',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Grenada': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '997007925.925926',
  'POPULATION YEAR 2016': '107',
  'REFUGEE ORIGIN YEAR 2016': 100},
 'Guam': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '5697000000',
  'POPULATION YEAR 2016': '163',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Guatemala': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '63767597193.9175',
  'POPULATION YEAR 2016': '16582',
  'REFUGEE ORIGIN YEAR 2016': 12534},
 'Guinea': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '8767143622.83101',
  'POPULATION YEAR 2016': '12396',
  'REFUGEE ORIGIN YEAR 2016': 17526},
 'Guinea-Bissau': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1036130506.53639',
  'POPULATION YEAR 2016': '1816',
  'REFUGEE ORIGIN YEAR 2016': 1635},
 'Guyana': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '3197225181.59806',
  'POPULATION YEAR 2016': '773',
  'REFUGEE ORIGIN YEAR 2016': 269},
 'Haiti': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '8724656126.49849',
  'POPULATION YEAR 2016': '10847',
  'REFUGEE ORIGIN YEAR 2016': 29661},
 'Honduras': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '20844284855.0025',
  'POPULATION YEAR 2016': '9113',
  'REFUGEE ORIGIN YEAR 2016': 10479},
 'Hong Kong SAR, China': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '309403880389.071',
  'POPULATION YEAR 2016': '7347',
  'REFUGEE ORIGIN YEAR 2016': 5},
 'Hungary': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '122879042001.915',
  'POPULATION YEAR 2016': '9818',
  'REFUGEE ORIGIN YEAR 2016': 2904},
 'Iceland': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '16783714958.4498',
  'POPULATION YEAR 2016': '334',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'India': {'ASYLUM NUMBER YEAR 2016': 652,
  'GDP YEAR 2015': '2089865410867.82',
  'POPULATION YEAR 2016': '1324171',
  'REFUGEE ORIGIN YEAR 2016': 7243},
 'Indonesia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '861256351277.359',
  'POPULATION YEAR 2016': '261115',
  'REFUGEE ORIGIN YEAR 2016': 13046},
 'Iran, Islamic Rep.': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '385874474398.59',
  'POPULATION YEAR 2016': '80277',
  'REFUGEE ORIGIN YEAR 2016': 94042},
 'Iraq': {'ASYLUM NUMBER YEAR 2016': 9016,
  'GDP YEAR 2015': '179640210726.448',
  'POPULATION YEAR 2016': '37203',
  'REFUGEE ORIGIN YEAR 2016': 315998},
 'Ireland': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '290617006703.972',
  'POPULATION YEAR 2016': '4773',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Isle of Man': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '6792417112.29947',
  'POPULATION YEAR 2016': '84',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Israel': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '299096404728.826',
  'POPULATION YEAR 2016': '8547',
  'REFUGEE ORIGIN YEAR 2016': 467},
 'Italy': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1832347450961.51',
  'POPULATION YEAR 2016': '60601',
  'REFUGEE ORIGIN YEAR 2016': 44},
 'Jamaica': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '14186886642.6685',
  'POPULATION YEAR 2016': '2881',
  'REFUGEE ORIGIN YEAR 2016': 1988},
 'Japan': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '4383076298081.86',
  'POPULATION YEAR 2016': '126995',
  'REFUGEE ORIGIN YEAR 2016': 53},
 'Jordan': {'ASYLUM NUMBER YEAR 2016': 34,
  'GDP YEAR 2015': '37517410281.6901',
  'POPULATION YEAR 2016': '9456',
  'REFUGEE ORIGIN YEAR 2016': 1889},
 'Kazakhstan': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '184388432148.715',
  'POPULATION YEAR 2016': '17797',
  'REFUGEE ORIGIN YEAR 2016': 2326},
 'Kenya': {'ASYLUM NUMBER YEAR 2016': 49,
  'GDP YEAR 2015': '63767539356.6051',
  'POPULATION YEAR 2016': '48462',
  'REFUGEE ORIGIN YEAR 2016': 7506},
 'Kiribati': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '169140538.696106',
  'POPULATION YEAR 2016': '114',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Korea, Rep.': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1382764027113.82',
  'POPULATION YEAR 2016': '51246',
  'REFUGEE ORIGIN YEAR 2016': 243},
 'Kosovo': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '6440501275.36875',
  'POPULATION YEAR 2016': '1816',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Kuwait': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '114567298105.683',
  'POPULATION YEAR 2016': '4053',
  'REFUGEE ORIGIN YEAR 2016': 1008},
 'Kyrgyz Republic': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '6678178340.45121',
  'POPULATION YEAR 2016': '6083',
  'REFUGEE ORIGIN YEAR 2016': 2546},
 'Lao PDR': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '14390391264.2607',
  'POPULATION YEAR 2016': '6758',
  'REFUGEE ORIGIN YEAR 2016': 7224},
 'Latvia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '27009231911.4428',
  'POPULATION YEAR 2016': '1960',
  'REFUGEE ORIGIN YEAR 2016': 165},
 'Lebanon': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '49459296463.2836',
  'POPULATION YEAR 2016': '6007',
  'REFUGEE ORIGIN YEAR 2016': 4709},
 'Lesotho': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2505886024.6573',
  'POPULATION YEAR 2016': '2204',
  'REFUGEE ORIGIN YEAR 2016': 5},
 'Liberia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '2034000000',
  'POPULATION YEAR 2016': '4614',
  'REFUGEE ORIGIN YEAR 2016': 6513},
 'Libya': {'ASYLUM NUMBER YEAR 2016': 1727,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '6293',
  'REFUGEE ORIGIN YEAR 2016': 8796},
 'Liechtenstein': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '6289165409.55908',
  'POPULATION YEAR 2016': '38',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Lithuania': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '41402022148.2053',
  'POPULATION YEAR 2016': '2872',
  'REFUGEE ORIGIN YEAR 2016': 64},
 'Luxembourg': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '57784495265.4378',
  'POPULATION YEAR 2016': '583',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Macao SAR, China': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '45361678146.5247',
  'POPULATION YEAR 2016': '612',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Macedonia, FYR': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '10051659161.1733',
  'POPULATION YEAR 2016': '2081',
  'REFUGEE ORIGIN YEAR 2016': 1705},
 'Madagascar': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '9744243420.48073',
  'POPULATION YEAR 2016': '24895',
  'REFUGEE ORIGIN YEAR 2016': 277},
 'Malawi': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '6373201160.03248',
  'POPULATION YEAR 2016': '18092',
  'REFUGEE ORIGIN YEAR 2016': 407},
 'Malaysia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '296434003328.639',
  'POPULATION YEAR 2016': '31187',
  'REFUGEE ORIGIN YEAR 2016': 443},
 'Maldives': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '4006531188.26486',
  'POPULATION YEAR 2016': '417',
  'REFUGEE ORIGIN YEAR 2016': 48},
 'Mali': {'ASYLUM NUMBER YEAR 2016': 96,
  'GDP YEAR 2015': '13100058099.804',
  'POPULATION YEAR 2016': '17995',
  'REFUGEE ORIGIN YEAR 2016': 156390},
 'Malta': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '10285547954.0777',
  'POPULATION YEAR 2016': '437',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Marshall Islands': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '179697900',
  'POPULATION YEAR 2016': '53',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Mauritania': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '4844223106.95469',
  'POPULATION YEAR 2016': '4301',
  'REFUGEE ORIGIN YEAR 2016': 36228},
 'Mauritius': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '11692287066.381',
  'POPULATION YEAR 2016': '1263',
  'REFUGEE ORIGIN YEAR 2016': 101},
 'Mexico': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '1152263780657.86',
  'POPULATION YEAR 2016': '127540',
  'REFUGEE ORIGIN YEAR 2016': 10367},
 'Micronesia, Fed. Sts.': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '315179700',
  'POPULATION YEAR 2016': '105',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Moldova': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '6512899540.34594',
  'POPULATION YEAR 2016': '3552',
  'REFUGEE ORIGIN YEAR 2016': 2291},
 'Monaco': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '0',
  'POPULATION YEAR 2016': '38',
  'REFUGEE ORIGIN YEAR 2016': 0},
 'Mongolia': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '11749620619.5962',
  'POPULATION YEAR 2016': '3027',
  'REFUGEE ORIGIN YEAR 2016': 2267},
 'Montenegro': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '4052913385.82677',
  'POPULATION YEAR 2016': '623',
  'REFUGEE ORIGIN YEAR 2016': 708},
 'Morocco': {'ASYLUM NUMBER YEAR 2016': 0,
  'GDP YEAR 2015': '101187079462.942',
  'POPULATION YEAR 2016': '35277',